<?php

namespace Huuhu\Php83813;
require './src/People.php';
require './src/Doing.php';
require './src/Info.php';
class Staff extends People implements \Doing,\Info// chi ke thua dc 1 class
{
    // cac PT cua Action
    // dc su dung boi Staff
    use \Action;
    public function xemTT()
    {
       echo 'Hien thi tin tuc';
    }
    public function profile()
    {
       echo 'Xem profile';
    }

    public function display()
    {
        echo "Thong tin nhan vien .... <br>";
    }

    public function login($username, $password)
    {
        echo 'Chao mừng nhân viên ' .$username;
    }
    public function xemThongTinLop()
    {
        echo  "Danh sach diem danh cho nhan vien ... <br>";
    }

    function displayInfo(){
        echo $this->name;
        echo '<br>';
        echo $this->add;
        $this->print();
        // ko truy cap duoc bien private
        //echo $this->realName;
        // goi biến và fun của lớp cha
    }
    public $role;
    public function __construct(string $name,
                                string $add,
    string $role)
    {
        // từ khoá parent để gọi contruct lớp cha
        parent::__construct($name, $add);
        $this->role = $role;
    }
    public function print()
    {
        // ghi đè phương thức
        parent::print(); // TODO: Change the autogenerated stub
        echo $this->role;
    }

    // loi ko ghi đè pt có từ khoá final
//    public function noOverriding(){
//
//    }
}